# Site settings
title: ULS Metadata and Discovery Unit
description: The Metadata and Discovery Unit provides metadata consultation, development, and production support for students, faculty, and staff at the University of Pittsburgh.
url: ""

baseurl: "/"


# Build settings
markdown: kramdown
source: .
destination: ./_site
permalink: /updates/:title
paginate: 5
paginate_path: "/updates/page:num"

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: "assets/img"
    values:
      image: true

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false

theme: jekyll-theme-minimal
